### PR TITLE
Implement clock and pwm modes

### PR DESCRIPTION
**Pull request by Drahoslav7**
Hi there.
I managed to add third pin mode - clock.

It is just clock (using `CM_GPnDIV` and `CM_GPnCTL` registers) - no pwm (yet).

Suggestions about better method/function naming are welcomed.
I tried to be consistent with current ideology, but not sure if it makes sense.

So this:   `PinMode(pin, rpio.Clock)` <=> `pin.Mode(rpio.Clock)` <=> `pin.Clock()` 
is analogical to:   `PinMode(pin, rpio.Output)` <=> `pin.Mode(rpio.Output)` <=> `pin.Output()`

and this:   `SetFreq(pin, 10000)` <=> `pin.Freq(10000)` <=> `???`
is analogical to:   `WritePin(pin, rpio.High)` <=> `pin.Write(rpio.High)` <=> `pin.High()`

Also not sure if it might make sense to add more public methods eg. for stopping/resetting clocks.

Please merge this if you like it.

### CODE REVIEW

**Comment by Drahoslav7** [comment]
So I also implemented simple pulse width modulation functionality.
For example, to set pin to 38kHz with 1/4 duty cycle you can do:
```
pin.Pwm()
pin.DutyCycle(1, 4)
pin.Freq(38000 * 4)
```
Dimming led example:
```
package main

import (
        "os"
        "time"
        "github.com/stianeikeland/go-rpio"
)

func main() {
        err := rpio.Open()
        if err != nil {
                os.Exit(1)
        }
        defer rpio.Close()

        pin := rpio.Pin(19)
        pin.Mode(rpio.Pwm)
        pin.Freq(60000)
        pin.DutyCycle(0, 32)

        for i := 0; i < 5; i++ {
                for i := uint32(0); i < 32; i++ { // increasing brightness
                        pin.DutyCycle(i, 32)
                        time.Sleep(time.Second/32)
                }
                for i := uint32(32); i != 0; i-- { // decreasing brightness
                        pin.DutyCycle(i, 32)
                        time.Sleep(time.Second/32)
                }
        }
}
```

**Comment by Albert221** [comment]
Can @stianeikeland merge this?

**Comment by Drahoslav7** [comment]
@stianeikeland, I know it's a lot of changes to review at once, I've done some refactoring even in your code and so on. But I would appreciate if you can check it and merge.

Or, if you do not want to maintain this repo anymore, then I would like to ask your permission to separate my fork from your repo and make my own stand-alone repository (with a different name perhaps and with mention, it is based on your work, of course.) which I will maintain by myself.

**Comment by stianeikeland** [comment]
Hey,
sorry for dropping the ball on this, I've been meaning to play with it but other things keep getting in the way.

Anyway, I've had a go at it this evening, and managed to make a LED phase in and out using an old Raspberry PI 1.

Code seems well written and works as intended, so I'll merge this is.

Would love to have an example program that demonstrate how to use PWM (the use of StartPwm, StopPwm, DutyCycle and Freq) like the blinker in `examples/`. Feel free to add that if you want :)

**Comment by Drahoslav7** [comment]
Great, thank you.
I think the example is ok. But I might change it just slightly - point out that result frequency of pin in PWM mode depends both on Freq and DutyCycle arguments - which may not seem obvious.

I noticed a tiny error in the code. Will make PR soon.

I would also consider adding a link to https://godoc.org/github.com/stianeikeland/go-rpio to readme - for people who do not know Golang so well and do not know this service exists, and just because it is convenient.

**Pull request merged**
